name: 小黑盒自动签到

on:
  schedule:
    - cron: '3 17 * * *' # UTC时间 17:03，对应北京时间每天凌晨 1:03 执行
  workflow_dispatch: # 允许手动点击按钮触发执行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install axios

      - name: Run Script
        env:
          BLACKBOX_COOKIE: ${{ secrets.BLACKBOX_COOKIE }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: node run.js
